export { createApp } from './createApp'
export { h } from './h'
export { renderSlots } from './utils/renderSlots'
export { createTextVnode } from './vnode'
export { getComponentInstance } from './component'
